'' Copyright (C) 2022 Alessandro "Sgorblex" Clerici Lorenzini and Edoardo "Miniman" Della Rossa
'
' This work may be distributed and/or modified under the
' conditions of the LaTeX Project Public License, either version 1.3
' of this license or (at your option) any later version.
' The latest version of this license is in
'   http://www.latex-project.org/lppl.txt
' and version 1.3 or later is part of all distributions of LaTeX
' version 2005/12/01 or later.
'
' This work has the LPPL maintenance status `maintained'.
'
' The Current Maintainer of this work is Alessandro Clerici Lorenzini
'
' This work consists of the files listed in work.txt


@startuml
hide empty members
scale 300 width


class Session
class SessionParameters
SessionParameters "1" *-- "n" VotingPaper
Session -- SessionParameters

interface VoteDecider
class AdultDecider

interface Vote
class CategoricalVote 
class OrdinalVote
class PreferencedVote
class ReferendumVote

VoteDecider <|-- AdultDecider
Vote <|-- CategoricalVote
Vote <|-- OrdinalVote
Vote <|-- PreferencedVote
Vote <|-- ReferendumVote

class VotingPaper
enum ElectionMethod
class Choice
VotingPaper -- VoteDecider 
VotingPaper "1" o-- "n" Vote
VotingPaper "1" *-- "n" Choice
VotingPaper -- ElectionMethod

class Person
Session "1" o-- "n" Person : Garanti

' class ResponsabileSeggio
' class Seggio
' Person <|-- ResponsabileSeggio
' Seggio "1" o-- "n" ResponsabileSeggio

@enduml
