@startuml
hide empty description
scale 10 height

state SessionCreated: cfr. Session Created Fsm

state "No Session Created" as NoSession {
	state "Login/Idle" as Login
	state RoleCheck <<choice>>
	[*] --> Login
	Login --> RoleCheck 
	RoleCheck --> UserLogged : role == USER
	RoleCheck --> AdminLogged : role == ADMIN
	RoleCheck -l-> Login : Wrong Credential
	AdminLogged --> SessionCreated : Session creating operation
	AdminLogged --> Login : Logout
	UserLogged --> Login : Logout
}

[*] --> NoSession


@enduml
