'' Copyright (C) 2022 Alessandro "Sgorblex" Clerici Lorenzini and Edoardo "Miniman" Della Rossa
'
' This work may be distributed and/or modified under the
' conditions of the LaTeX Project Public License, either version 1.3
' of this license or (at your option) any later version.
' The latest version of this license is in
'   http://www.latex-project.org/lppl.txt
' and version 1.3 or later is part of all distributions of LaTeX
' version 2005/12/01 or later.
'
' This work has the LPPL maintenance status `maintained'.
'
' The Current Maintainer of this work is Alessandro Clerici Lorenzini
'
' This work consists of the files listed in work.txt


@startuml
actor "Web client" as WC
participant WebServer as WS
participant Session as S
participant SpringSecurity as SS

WC -> WS : Authentication Request
WC <-- WS : Authentication Response
WS -> SS : Authentication Check Request
WS <-- SS : Authentication Check Response

alt Authentication successful
   WS -> S : getRoles(loggedUser);
   WS <-- S : user roles
   alt Session is ended && (userRole == guarantor || userRole == admin)
      WS -> S : getPapers();
      WS <-- S : VotingPaper list
      loop foreach VotingPaper
         WS -> S : getResult();
         WS <-- S : Result response
      end
      WS -> WC : '/result' resource
   end
else Authentication failed or user not guarantor
   WS -> WC !! : Error Message
end
@enduml
