@startuml
actor "Web client" as WC
participant WebServer as WS
participant Session as S
participant SpringSecurity as SS

WC -> WS : Authentication Request
WC <-- WS : Authentication Response
WS -> SS : Authentication Check Request
WS <-- SS : Authentication Check Response

alt Authentication successful
   WS -> S : getRoles(loggedUser);
   WS <-- S : user roles
   alt Session is ended && (userRole == guarantor || userRole == admin)
      WS -> S : getPapers();
      WS <-- S : VotingPaper list
      loop foreach VotingPaper
         WS -> S : getResult();
         WS <-- S : Result response
      end
      WS -> WC : '/result' resource
   end
else Authentication failed or user not guarantor
   WS -> WC !! : Error Message
end
@enduml
