@startuml
actor "Persona fisica" as P
participant "Client" as C
participant "Authenticator" as A  
participant "Amministratore\nSessione di Voto" as ASess
participant "Server" as S 
participant "Garanti" as G

P -> C : Authentication Request
C -> A : Forwarded Authentication Request
A -> S : Forwarded Authentication Request


alt "Credenziali corrette"

        S -> A: Authentication Accepted
	S -> ASess **: crea
        A -> C: Authentication Accepted
        C -> P: Authentication Accepted
	P -> C: Start della sessione di voto
	C -> ASess: Start della sessione di voto
    	group assert 
		G -> S: Approvazione\nconfigurazione
   	end
	ASess -> S: Start della sessione di voto
	P -> C: esci
	C -> ASess !!: esci


else Credenziali rifiutate

    S -> A: Authentication Refused
    A -> C: Authentication Refused
    C -> P: Authentication Refused

end
@enduml

else Credenziali rifiutate

    S -> A: Authentication Refused

end
@enduml
