@startuml
actor "Web client" as WC
participant WebServer as WS
participant VotingPaper as VP
participant "Sub-VotingPaper" as SVP
participant SpringSecurity as SS
participant Session as S

WC -> WS : Authentication Request
WC <-- WS : Authentication Response
WS -> SS : Authentication Check Request
WS <-- SS : Authentication Check Response

alt Authentication successful
    WS <- S : getPapers();
    WS -> WC : '/vote' resource
    loop for each voting paper
        S -> VP ** : Puntatore a VotingPaper
        WS <- VP : getMethod()
        alt method == ElectionMethod.PREFERENCED
            loop for each sub-voting paper
            S -> SVP ** : Puntatore a VotingPaper
	    VP <- WS : getChoices()
	    WS -> WC : Display choices
            WC -> WS : Select the choice
            WS -> SVP : addVote()
            deactivate SVP
            end
        else method != ElectionMethod.PREFERENCED
	    VP <- WS : getChoices()
	    WS -> WC : Display choices
            WC -> WS : Select the choice
            WS -> VP : addVote()
        deactivate VP
    end
    end
else Authentication failed
   WS -> WC !! : Error Message
end

@enduml
